import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ContactLayout from '@/components/ContactLayout'
import TopMenuLayout from '@/components/TopMenuLayout'
import NextAuthProvider from '@/provider/NextAuthProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = getServerSession(authOptions);

  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <body className={`${inter.className} text-black`}>
          <div className="flex flex-col w-screen fixed top-0 z-30"> 
            <ContactLayout/>
            <TopMenuLayout/>
          </div>
          {children}
        </body>
      </NextAuthProvider>
    </html>
  )
}
